%%%-------------------------------------------------------------------
%%% @doc Router module for bsh_http_handler
%%% Generated by rebar3_openapi
%%% Provides trails() compatibility wrapper
%%% @end
%%%-------------------------------------------------------------------
-module(bsh_http_router).

%% API exports
-export([trails/0, get_paths/1, get_operations/0]).

%% Behavior for trails compatibility
-behaviour(trails_handler).

%%%===================================================================
%%% API - Trails Compatibility
%%%===================================================================

%% @doc Returns trails for cowboy_routes_manager
trails() ->
    Paths = get_paths(bsh_http_logic_handler),
    lists:flatten([PathList || {'_', PathList} <- Paths]).

%% @doc Get paths with handler module
get_paths(LogicModule) ->
    [{'_', [
        {<<"/api/butler_shared/diagnose/infra">>, bsh_http_handler, {'diagnose_infra', <<"POST">>, bsh_http_logic_handler}},
        {<<"/api/butler_shared/v1/logging/debug">>, bsh_http_handler, {'get_debug_logging_status', <<"GET">>, bsh_http_logic_handler}},
        {<<"/api/butler_shared/v1/logging/debug/disable">>, bsh_http_handler, {'disable_debug_logging', <<"POST">>, bsh_http_logic_handler}},
        {<<"/api/butler_shared/v1/logging/debug/enable">>, bsh_http_handler, {'enable_debug_logging', <<"POST">>, bsh_http_logic_handler}},
        {<<"/api/{service_name}/v1/diagnose">>, bsh_http_handler, {'diagnose_service_v1', <<"POST">>, bsh_http_logic_handler}},
        {<<"/api/{service_name}/v2/diagnose">>, bsh_http_handler, {'diagnose_service_v2', <<"POST">>, bsh_http_logic_handler}},
        {<<"/v1/health">>, bsh_http_handler, {'health_check', <<"GET">>, bsh_http_logic_handler}},
        {<<"/v1/status">>, bsh_http_handler, {'get_service_status', <<"GET">>, bsh_http_logic_handler}}
    ]}].

%% @doc Get all operations metadata
get_operations() ->
    [
        {<<"/api/butler_shared/diagnose/infra">>, <<"post">>, 'diagnose_infra'},
        {<<"/api/butler_shared/v1/logging/debug">>, <<"get">>, 'get_debug_logging_status'},
        {<<"/api/butler_shared/v1/logging/debug/disable">>, <<"post">>, 'disable_debug_logging'},
        {<<"/api/butler_shared/v1/logging/debug/enable">>, <<"post">>, 'enable_debug_logging'},
        {<<"/api/{service_name}/v1/diagnose">>, <<"post">>, 'diagnose_service_v1'},
        {<<"/api/{service_name}/v2/diagnose">>, <<"post">>, 'diagnose_service_v2'},
        {<<"/v1/health">>, <<"get">>, 'health_check'},
        {<<"/v1/status">>, <<"get">>, 'get_service_status'}    ].
